FROM openjdk:8-jdk-alpine3.8

# 设置时区为上海
RUN ln -sf /usr/share/zoneinfo/Asia/Chongqing /etc/localtime && echo 'Asia/Chongqing' >/etc/timezone

VOLUME /tmp
WORKDIR /home/app

# install dumb-init; helps dockerized java handle signals properly
COPY bin/dumb-init_1.2.5_x86_64 /usr/bin/dumb-init
ENTRYPOINT ["dumb-init", "--"]

COPY jvm-sandbox-repeater/sandbox /home/app/sandbox/
COPY dist/sandbox-module /home/app/.sandbox-module/

# process will run as non-root `app` user
RUN chmod +x /usr/bin/dumb-init && \
    addgroup app && \
    adduser -s /bin/bash -h /home/app -G app -D app && \
    chown -R app:app .

USER app

ENV JVM_OPTS="-Xms64m -Xmx1024m -Dspring.profiles.active=test"
ENV JVM_REPEATER="-javaagent:/home/app/sandbox/lib/sandbox-agent.jar=server.port=8820"

EXPOSE 8820/TCP

CMD java $JVM_OPTS $JVM_REPEATER -Djava.security.egd=file:/dev/./urandom -jar /home/app/app.jar


